#!/bin/zsh
# Получаем информацию о VCS перед каждой новой командной строкой.

autoload -Uz vcs_info   # Импортируем функцию vcs_info.

# Этот паттерн (переопределить вызываемую функцию и вызвать ее повторно внизу
# файла) позволяет выполнить setup только при первом вызове.
# $0 содержит имя текущей функции.
$0() {
  local -i fd=-1  # `fd` = file descriptor

  # Запускаем асинхронный процесс, чтобы не тормозить в крупных репозиториях.
  # <( ... ) создает процесс, из которого можно читать.
  # exec {fd}< открывает новый файловый дескриптор, кладет его номер в $fd,
  # подключает к процессу и сразу возвращает управление: процесс работает
  # асинхронно и неблокирующе.
  exec {fd}< <(
    vcs_info
    print -r -- $vcs_info_msg_0_
  )

  # Подвешиваем callback-виджет на этот fd.
  zle -Fw "$fd" prompt_launchpad_vcs-info
}

# Создаем виджет, который вызывает функцию ниже.
zle -N prompt_launchpad_vcs-info
prompt_launchpad_vcs-info() {
  local -i fd=$1  # -i задает целочисленный тип.
  local REPLY
  {
    zle -F "$fd"  # Отвязываем callback от fd.
    read -ru$fd   # Читаем из fd в $REPLY.

    [[ $RPS1 == $REPLY ]] &&
        return   # Не перерисовываем, если изменений нет.

    RPS1=$REPLY

    [[ $CONTEXT == start ]] &&
        zle .reset-prompt   # Перерисовываем только когда $RPS1 видим.
  } always {
    exec {fd}<&-  # Закрываем файловый дескриптор.
  }
}

# Форматируем вывод vcs_info, который precmd использует для $RPS1.
#     %a: текущее действие (например, rebase)
#     %c: индексированные изменения (staged)
#     %u: неиндексированные изменения (unstaged)
#     %b: ветка
# https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#vcs_005finfo-Configuration
() {
  "$@"           formats          "%c%u%F{14}%b%f"  # 14 — ярко-голубой.
  "$@"     actionformats  "%F{9}%a %c%u%F{14}%b%f"  #  9 — ярко-красный.
  "$@"         stagedstr  "%F{10}+"   # Значение для %c. 10 — ярко-зеленый.
  "$@"       unstagedstr  "%F{11}*"   # Значение для %u. 11 — ярко-желтый.
  "$@"  check-for-changes yes         # Включить %c и %u.
} zstyle ':vcs_info:*'

$0 "$@"
